version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5932:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
  test-db:
    image: postgres:13
    ports:
      - 5934:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
